# 1. IDENTIFICACIÓN DE LA APLICACIÓN
spring.application.name=EnergyBackend

# 2. CONFIGURACIÓN DEL PUERTO (Usa este en Postman: http://localhost:8081)
server.port=8081

# 3. CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
# Asegúrate de que la base de datos 'energy_db' exista en tu pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. CONFIGURACIÓN DE JPA / HIBERNATE
# 'update' mantiene tus datos y solo actualiza la estructura si cambias el Model
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. DESACTIVAR SEGURIDAD POR DEFECTO (Para que Postman no pida login)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# 6. LOGGING Y TRAZAS
# Esto te permite ver en la consola si los archivos se están cargando o si hay errores
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO

# 7. CONFIGURACIÓN DE CARGA DE ARCHIVOS (Opcional pero recomendado)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB