# Configuración de Servidor
server.port=8081

# Configuración de Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Mostrar Logs de Debug para ver los Inserts
logging.level.org.hibernate.SQL=DEBUG
# Cambia 'update' por 'create' para que borre y recree las tablas al iniciar
security.jwt.secret=yo_soy_el_secreto_pa_generar_los_tokensitos
security.jwt.expiration-ms=86400000
