server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/energy_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.hibernate.SQL=DEBUG

security.jwt.secret=TXlfU3VwZXJfU2VjcmV0X0tleV9QYXJhX0pXVF8yMDI2X0VuZXJneV9CYWNrZW5k
security.jwt.expiration-ms=86400000